{
    "name": " Perfumer Development ",
    "summary": "Codex Perfumer customisation(CRM,sales,Estimation)",
    "version": "17.0.0.0.0",
    "author": "Fahad Hassan",
    "license": "AGPL-3",
    'website': "https://www.codexitns.com/",
    "category": "approval",
    "depends": ["base","crm","product","stock",'purchase_stock','sale','cdx_dynamic_approval','mrp','sale_management','hr_timesheet'],
    "data": [
        'data/ir_sequence.xml',
        'data/sequence.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'views/crm_lead_view.xml',
        # 'views/cdx_estimation_view.xml',
        'views/view_saleorder.xml',
        'views/view_cdx_estimation_line.xml',
        'views/view_sale_estimation_line.xml',
        'views/material_request.xml',
        "views/purchase_requisition.xml",
        'views/stock_location.xml',
        'views/mrp_production_views.xml',
        "views/mrp_bom_views.xml",
        "views/product_view.xml",
        "views/stock_picking.xml",
        "views/res_users_view.xml",
        "views/view_purchase.xml",
        'views/view_action_activity.xml',
        # 'views/cdx_crm_lead_form_inherited.xml',
        'wizard/material_request_wizard.xml',
        'wizard/wizard.xml',
        'wizard/popup_msg.xml',
        
        'reports/report_sale_order.xml',
        'reports/report_invoice_bom.xml',
        'reports/report_action.xml',
        'wizard/advance_payment_wizard_view.xml'
    ],
    'assets': {
        'web.assets_backend': [
            'cdx_perfumer/static/src/js/dialog.js',
            'cdx_perfumer/static/src/js/widget.js',
            "cdx_perfumer/static/src/xml/widget.xml",
            "cdx_perfumer/static/src/js/stock_availability_widget.js",
            "cdx_perfumer/static/src/xml/stock_availability_widget.xml",
            'cdx_perfumer/static/src/js/timer.js',
            'cdx_perfumer/static/src/xml/timer.xml',
            'cdx_perfumer/static/src/css/style.css',
            # 'cdx_perfumer/static/src/js/section_wise_subtotall.js',
        ],
    },

    "installable": True,
    "auto_install":False,
}
