from . import crm
from . import estimation
from . import sale_order
from . import sale_line_estimation_line
from . import purchase_requisition
from . import purchase
from . import material_request
from . import stock_picking
from . import mrp_production
from . import stock_location
from . import mrp_bom
from . import product
from . import res_users
from . import account_payment
from . import cdx_crm_lead_inherited